backend:
  name: github
  repo: baogezhao/888  # 若改名，请修改为 baoge/888
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章管理"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "文章标题", name: "title", widget: "string" }
      - { label: "作者", name: "author", widget: "string", default: "baoge" }
      - { label: "发布时间", name: "date", widget: "datetime" }
      - { label: "文章来源", name: "source", widget: "string", default: "原创" }
      - { label: "缩略图/封面图", name: "thumbnail", widget: "image", required: false }
      - { label: "文章摘要（若留空，自动化脚本将截取正文前100字）", name: "summary", widget: "string", required: false }
      - { label: "正文内容", name: "body", widget: "markdown" }
